version: '3'

services:
  websocket-server:
    image: ghcr.io/yourusername/talk-to-figma-claude:latest
    container_name: talk-to-figma
    ports:
      - "3600:3600"
    restart: unless-stopped
    environment:
      - WEBSOCKET_PORT=3600
      - WEBSOCKET_HOST=0.0.0.0
